name: 'Deploy Kubernetes Interview Challenge'
description: 'Kubeconfig variable'
inputs:
  kube-config:  # id of input
    description: 'Kubeconfig string'
    required: true
    default: 'kubeconfig'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.kube-config }}
