apiVersion: apps/v1
kind: Deployment
metadata:
  name: interview-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interview
  template:
    metadata:
      labels:
        app: interview
    spec:
      dnsPolicy: "Default"
      dnsConfig:
        nameservers:
          - "203.0.113.123"  # Invalid nameserver
        searches:
          - google.com  # Wrong search path
        options:
         - name: ndots
           value: "1"
      containers:
      - name: main
        image: becloudready/k8s-troubleshooting-scenarios:7.0.0
        command: ["python3", "/app/troubleshoot_scenarios.py"]
        volumeMounts:
        - name: config-vol
          mountPath: /etc/app
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
      volumes:
      - name: config-vol
        configMap:
          name: app-config
          items:
          - key: config1.yml  # Incorrect key
            path: config.yaml
